version: "3"

services:
  prometheus-server: 
    image: "bitnami/prometheus:2.44.0"
    volumes:
      - type: volume
        source: prometheus_data
        target: /opt/bitnami/prometheus/data
      - type: bind
        source: ./prometheus.yml
        target: /opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "9090:9090"
  consul-server:
    image: "hashicorp/consul:1.15"
    ports:
      - "8500:8500"


volumes:
  prometheus_data:
